pageInfo:
  title: Xavier
  description: ''
  navLinks: null
appConfig:
  theme: vaporwave
  layout: auto
  iconSize: medium
sections:
  - name: Media
    icon: fas fa-photo-video
    items:
      - title: Jellyfin
        icon: hl-jellyfin
        url: http://xavier.local:8096
        target: newtab
        id: 0_480_jellyfin
    displayData:
      sortBy: alphabetical
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
  - name: Monitoring
    icon: fas fa-monitor-heart-rate
    displayData:
      sortBy: alphabetical
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Cockpit
        icon: cockpit-logo.svg
        url: http://xavier.local:9090
        target: newtab
        id: 0_1062_cockpit
  - name: Home Control
    icon: fas fa-house-signal
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: Home Assistant
        icon: hl-home-assistant
        url: http://homeassistant.local:8123
        target: newtab
        id: 0_1162_homeassistant
